name: Download and Process Reports

on:
  schedule:
    - cron: '0 0 * * *'  # This will run daily at midnight
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  download-and-process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Download JSON data
      run: curl -XGET 'http://distribution.virk.dk/offentliggoerelser/_search' -H 'Content-Type: application/json' -d '{"query": {"bool": {"must": [{"term": {"dokumenter.dokumentMimeType": "application"}},{"term": {"dokumenter.dokumentMimeType": "xml"}},{"range": {"offentliggoerelsesTidspunkt": {"gt": "2018-06-21T00:00:00.001Z", "lt": "2018-06-21T23:59:59.505Z"}}}]}},"size": 2999}' -o output.json

    - name: Run Python script
      run: python script.py  # Replace with the path to your Python script

    - name: Commit and push reports
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add reports
        git commit -m "Add downloaded reports"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
